# yarn berry の設定ファイル
# cf. https://yarnpkg.com/configuration/manifest

# yarn 本体を Git にコミットして使う
yarnPath: .yarn/releases/yarn-3.2.2.cjs

plugins:
  # yarn workspace 用のプラグイン
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

# パッケージのインストール方法を pnp ではなく node_modules にする
nodeLinker: node-modules
